set(INCLUDE_DIRECTORIES "${CMAKE_CURRENT_SOURCE_DIR}/program/include")
set(
  SYSTEM_INCLUDE_DIRECTORIES
  "${CMAKE_CURRENT_BINARY_DIR}/external/SDL2/include"
  "${CMAKE_CURRENT_BINARY_DIR}/external/SDL2/include-config-${CMAKE_BUILD_TYPE_LOWER}"
  "${CMAKE_CURRENT_BINARY_DIR}/external/SDL2/include-config-${CMAKE_BUILD_TYPE_LOWER}/SDL2"
  "${CMAKE_CURRENT_SOURCE_DIR}/external/ftxui/include"
  "${CMAKE_CURRENT_SOURCE_DIR}/external/sqlite/include"
  "${CMAKE_CURRENT_SOURCE_DIR}/external/taglib/include"
)
file(GLOB HEADER_FILES "${CMAKE_CURRENT_SOURCE_DIR}/program/include/*.*")
file(
  GLOB SOURCE_FILES
  "${CMAKE_CURRENT_SOURCE_DIR}/program/source/*.*"
  "${CMAKE_CURRENT_SOURCE_DIR}/external/sqlite/source/*.*"
)
source_group("Header Files" FILES "${HEADER_FILES}")
source_group("Source Files" FILES "${SOURCE_FILES}")
set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE BOOL "")
set(CMAKE_CXX_STANDARD "20" CACHE STRING "")
set(BUILD_SHARED_LIBS OFF CACHE BOOL "")
set(FORCE_STATIC_VCRT ON CACHE BOOL "")
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
set(WARNING_FLAGS "/W4")
set(LINKER_FLAGS "/INCREMENTAL:NO")

set(WITH_ZLIB OFF CACHE BOOL "")
set(BUILD_BINDINGS OFF CACHE BOOL "")
set(BUILD_TESTING OFF CACHE BOOL "")
set(ENABLE_STATIC_RUNTIME ON CACHE BOOL "")
set(utf8cpp_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/external/taglib/3rdparty/utfcpp/source")
list(APPEND LIBRARIES "tag")
list(APPEND COMPILER_DEFINITIONS "TAGLIB_STATIC")

set(SDL_TEST_ENABLED_BY_DEFAULT OFF CACHE BOOL "")
set(SDL_TEST OFF CACHE BOOL "")
set(SDL2_DISABLE_INSTALL ON CACHE BOOL "")
set(SDL2_DISABLE_UNINSTALL ON CACHE BOOL "")
set(SDL2_DISABLE_SDL2MAIN ON CACHE BOOL "")
set(SDL2MIXER_OPUS OFF CACHE BOOL "")
set(SDL2MIXER_WAVPACK OFF CACHE BOOL "")
set(SDL2MIXER_MOD OFF CACHE BOOL "")
set(SDL2MIXER_FLAC OFF CACHE BOOL "")
set(SDL2MIXER_MIDI OFF CACHE BOOL "")
set(SDL2MIXER_GME OFF CACHE BOOL "")
set(SDL2MIXER_OGG OFF CACHE BOOL "")
set(SDL2MIXER_VORBIS "" CACHE STRING "")
list(APPEND LIBRARIES "SDL2::SDL2-static" "SDL2_mixer::SDL2_mixer-static")
list(APPEND COMPILER_DEFINITIONS "SDL_MAIN_HANDLED")

set(FTXUI_ENABLE_INSTALL OFF CACHE BOOL "")
list(APPEND LIBRARIES "ftxui::component" "ftxui::dom" "ftxui::screen")
